# Transacciones de Ingresos por Ventas - Exploración de Datos

Este notebook carga el conjunto de datos de transacciones unificado y presenta una vista previa de las primeras filas.

## Importacion de librerias

In [1]:
import pandas as pd

## Carga del dataset

In [2]:
# Cargar el conjunto de datos de transacciones combinadas
dataset_path = "dataset/transactionRevenue_combined.csv"
df = pd.read_csv(dataset_path, low_memory=False)

# Mostrar las primeras filas
df.head()

,line_id,receipt_id,date,hour,retail_year,retail_quarter,retail_month,retail_week,ly_date_key,date_key,...,promo_name,promo_amt,is_return,return_reason,return_lag_days,orig_location_name,rpt_ignored,txn_type,is_employee_sale,is_wholesale
0,20b3fe6a-df9d-4767-8d60-08e962dff174,10a4aa3d-b748-4386-877c-89aab6dc3a52,2022-01-02,12,2022,1,1,1,20210103,20220102,...,NaN,NaN,False,NaN,NaN,NaN,False,Sale,False,False
1,9d71e9fa-bdad-4430-a1a5-3f0f99fd75f2,8f7621da-16b1-4ed2-9f31-1086c704dafc,2022-01-03,14,2022,1,1,1,20210104,20220103,...,NaN,NaN,False,NaN,13.0,Catbird SOHO,False,Mixed,False,False
2,00ccdfeb-1827-44f9-8530-96a880aebb4c,710c131d-8e7e-4777-8499-bca52b02bd10,2022-01-03,18,2022,1,1,1,20210104,20220103,...,NaN,NaN,False,NaN,NaN,NaN,False,Sale,False,False
3,43f45aad-7528-47c9-baa0-10e202d992d6,d13f8833-d50e-43b2-8ee1-20f6771cb7d9,2022-01-03,16,2022,1,1,1,20210104,20220103,...,NaN,NaN,True,Z OTHER - Dont Use,NaN,NaN,False,Mixed,False,False
4,88c545f4-8b4e-4785-b401-43afa4fffaba,aff19ce9-12dd-422b-957a-dfd123cf8004,2022-01-03,15,2022,1,1,1,20210104,20220103,...,NaN,NaN,False,NaN,NaN,NaN,False,Sale,False,False

In [7]:
# Conocer las dimensiones del dataset
df.shape

(2437140, 40)

## Columnas del Dataset

Listado de las 40 columnas del dataset junto con sus tipos de datos.

In [8]:
# Mostrar cada columna del dataset en formato de tabla vertical
pd.set_option('display.max_rows', None)
pd.DataFrame({
    'Nombre de Columna': df.columns,
    'Tipo de Dato': df.dtypes.values
})

           Column Name Data Type
0              line_id    object
1           receipt_id    object
2                 date    object
3                 hour     int64
4          retail_year     int64
5       retail_quarter     int64
6         retail_month     int64
7          retail_week     int64
8          ly_date_key     int64
9             date_key     int64
10       location_name    object
11            loc_city    object
12           loc_state    object
13              is_web      bool
14             item_id    object
15          department    object
16               class    object
17           subclass1    object
18               brand    object
19         item_season   float64
20         customer_id    object
21      ship_to_postal    object
22        associate_id    object
23                 qty   float64
24           net_sales   float64
25         gross_sales   float64
26                cogs   float64
27              margin   float64
28      discount_total   float64
29            markdown   float64
30          promo_name   float64
31           promo_amt   float64
32           is_return      bool
33       return_reason    object
34     return_lag_days   float64
35  orig_location_name    object
36         rpt_ignored      bool
37            txn_type    object
38    is_employee_sale      bool
39        is_wholesale      bool

## Resumen Estadístico

Visión general de las columnas numéricas y categóricas del dataset.

In [3]:
# Estadísticas descriptivas de todas las columnas (numéricas y categóricas)
df.describe(include='all')

,line_id,receipt_id,date,hour,retail_year,retail_quarter,retail_month,retail_week,ly_date_key,date_key,...,promo_name,promo_amt,is_return,return_reason,return_lag_days,orig_location_name,rpt_ignored,txn_type,is_employee_sale,is_wholesale
count,2437140,2437140,2437140,2.437140e+06,2.437140e+06,2.437140e+06,2.437140e+06,2.437140e+06,2.437140e+06,2.437140e+06,...,0.0,0.0,2437140,155063,199795.000000,204208,2437140,2437140,2437140,2437140
unique,2437140,1336504,1702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2,67,NaN,28,2,5,1,2
top,20b3fe6a-df9d-4767-8d60-08e962dff174,e53bc501-adbe-4630-8936-5e793b1f3bf5,2022-11-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,Sellable Exchange - Diff Size,NaN,Web Warehouse,False,Sale,False,False
freq,1,188,6753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2278330,16858,NaN,96132,2408381,2167322,2437140,2437088
mean,NaN,NaN,NaN,1.270690e+01,2.023887e+03,2.669983e+00,7.151570e+00,2.913193e+01,2.022966e+07,2.023963e+07,...,NaN,NaN,NaN,NaN,123.866783,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,4.370811e+00,1.317463e+00,1.127597e+00,3.572777e+00,1.550746e+01,1.315661e+04,1.314548e+04,...,NaN,NaN,NaN,NaN,241.033831,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,0.000000e+00,2.022000e+03,1.000000e+00,1.000000e+00,1.000000e+00,2.021010e+07,2.022010e+07,...,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,1.100000e+01,2.023000e+03,2.000000e+00,4.000000e+00,1.600000e+01,2.022050e+07,2.023050e+07,...,NaN,NaN,NaN,NaN,7.000000,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,1.300000e+01,2.024000e+03,3.000000e+00,7.000000e+00,3.000000e+01,2.023070e+07,2.024070e+07,...,NaN,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,1.600000e+01,2.025000e+03,4.000000e+00,1.100000e+01,4.500000e+01,2.024081e+07,2.025081e+07,...,NaN,NaN,NaN,NaN,107.000000,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,2.300000e+01,2.026000e+03,4.000000e+00,1.200000e+01,5.300000e+01,2.025090e+07,2.026083e+07,...,NaN,NaN,NaN,NaN,3225.000000,NaN,NaN,NaN,NaN,NaN

In [9]:
# Visualizar las primeras 5 filas del dataset
df.head()

,line_id,receipt_id,date,hour,retail_year,retail_quarter,retail_month,retail_week,ly_date_key,date_key,...,promo_name,promo_amt,is_return,return_reason,return_lag_days,orig_location_name,rpt_ignored,txn_type,is_employee_sale,is_wholesale
0,20b3fe6a-df9d-4767-8d60-08e962dff174,10a4aa3d-b748-4386-877c-89aab6dc3a52,2022-01-02,12,2022,1,1,1,20210103,20220102,...,NaN,NaN,False,NaN,NaN,NaN,False,Sale,False,False
1,9d71e9fa-bdad-4430-a1a5-3f0f99fd75f2,8f7621da-16b1-4ed2-9f31-1086c704dafc,2022-01-03,14,2022,1,1,1,20210104,20220103,...,NaN,NaN,False,NaN,13.0,Catbird SOHO,False,Mixed,False,False
2,00ccdfeb-1827-44f9-8530-96a880aebb4c,710c131d-8e7e-4777-8499-bca52b02bd10,2022-01-03,18,2022,1,1,1,20210104,20220103,...,NaN,NaN,False,NaN,NaN,NaN,False,Sale,False,False
3,43f45aad-7528-47c9-baa0-10e202d992d6,d13f8833-d50e-43b2-8ee1-20f6771cb7d9,2022-01-03,16,2022,1,1,1,20210104,20220103,...,NaN,NaN,True,Z OTHER - Dont Use,NaN,NaN,False,Mixed,False,False
4,88c545f4-8b4e-4785-b401-43afa4fffaba,aff19ce9-12dd-422b-957a-dfd123cf8004,2022-01-03,15,2022,1,1,1,20210104,20220103,...,NaN,NaN,False,NaN,NaN,NaN,False,Sale,False,False

In [5]:
df.tail()

,line_id,receipt_id,date,hour,retail_year,retail_quarter,retail_month,retail_week,ly_date_key,date_key,...,promo_name,promo_amt,is_return,return_reason,return_lag_days,orig_location_name,rpt_ignored,txn_type,is_employee_sale,is_wholesale
2437135,525485e2-ea67-4ff7-929e-2d737649513b,6b184979-0e0e-4691-a6f7-225099077388,2024-12-26,13,2024,4,12,52,20231228,20241226,...,NaN,NaN,False,NaN,NaN,NaN,False,Sale,False,False
2437136,31e2500f-1069-4109-bb85-f83d9c5b9eea,3d2a076f-b5c9-45fc-b76c-c0999f178482,2024-12-26,14,2024,4,12,52,20231228,20241226,...,NaN,NaN,False,NaN,NaN,NaN,False,Sale,False,False
2437137,815e0cdc-4886-427f-adaf-fe1b3e4255be,dad15974-c93b-4a14-bdf9-c35f627d2ecd,2024-12-26,14,2024,4,12,52,20231228,20241226,...,NaN,NaN,False,NaN,NaN,NaN,False,Sale,False,False
2437138,c78e8f37-8dd6-4528-be6e-d437dbf99fa1,9a55ae3f-db1e-4820-ba3f-220165a36f9d,2024-12-26,14,2024,4,12,52,20231228,20241226,...,NaN,NaN,False,NaN,NaN,NaN,False,Sale,False,False
2437139,f6f709da-2c57-4b5e-b25b-a0c2bfd155de,2cf944c7-1c24-4579-9c2b-ada274fcfcfb,2024-12-26,13,2024,4,12,52,20231228,20241226,...,NaN,NaN,False,NaN,NaN,NaN,False,Sale,False,False

In [10]:
# Comprobar la información general del dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2437140 entries, 0 to 2437139
Data columns (total 40 columns):
 #   Column              Dtype
---  ------              -----
 0   line_id             object
 1   receipt_id          object
 2   date                object
 3   hour                int64
 4   retail_year         int64
 5   retail_quarter      int64
 6   retail_month        int64
 7   retail_week         int64
 8   ly_date_key         int64
 9   date_key            int64
 10  location_name       object
 11  loc_city            object
 12  loc_state           object
 13  is_web              bool
 14  item_id             object
 15  department          object
 16  class               object
 17  subclass1           object
 18  brand               object
 19  item_season         float64
 20  customer_id         object
 21  ship_to_postal      object
 22  associate_id        object
 23  qty                 float64
 24  net_sales           float64
 25  gross_sales         float64
 26  cogs                float64
 27  margin              float64
 28  discount_total      float64
 29  markdown            float64
 30  promo_name          float64
 31  promo_amt           float64
 32  is_return           bool
 33  return_reason       object
 34  return_lag_days     float64
 35  orig_location_name  object
 36  rpt_ignored         bool
 37  txn_type            object
 38  is_employee_sale    bool
 39  is_wholesale        bool
dtypes: bool(5), float64(11), int64(7), object(17)
memory usage: 662.4+ MB

## Limpieza Contable del Dataset

De acuerdo con el diccionario de datos y las reglas contables del negocio:
1. **Tarjetas de Regalo (`rpt_ignored == True`):** Se eliminan estas filas (~28,759 registros), ya que representan pasivos contables por emisión/carga de tarjetas de regalo con costo de bienes vendidos ($0 COGS) que no deben sumarse en los reportes de ingresos.

2. **Anulaciones de Transacciones (`txn_type` en `['Reversal', 'Reversed']`):** Se excluyen los registros anulados (208 filas), conservando únicamente transacciones efectivas (`'Sale'`, `'Return'` y `'Mixed'`).

In [12]:
# 1. Identificación y cuantificación de filas a excluir
filtro_tarjetas = df['rpt_ignored'] == True
filtro_anulaciones = df['txn_type'].isin(['Reversal', 'Reversed'])

total_inicial = len(df)
total_tarjetas = filtro_tarjetas.sum()
total_anulaciones = filtro_anulaciones.sum()
total_excluidas = (filtro_tarjetas | filtro_anulaciones).sum()

print(f"Total de filas iniciales: {total_inicial:,}")
print(f"Filas de tarjetas de regalo a eliminar (rpt_ignored == True): {total_tarjetas:,}")
print(f"Filas de anulaciones a eliminar (Reversal/Reversed): {total_anulaciones:,}")
print(f"Total de filas contablemente excluidas: {total_excluidas:,}")

# 2. Aplicar el filtrado contable
# Se conservan únicamente registros con rpt_ignored == False y txn_type en ['Sale', 'Return', 'Mixed']
df = df[~filtro_tarjetas & ~filtro_anulaciones].copy()

print(f"\nTotal de filas resultantes en df: {len(df):,}")

Total de filas iniciales: 2,437,140
Filas de tarjetas de regalo a eliminar (rpt_ignored == True): 28,759
Filas de anulaciones a eliminar (Reversal/Reversed): 208
Total de filas contablemente excluidas: 28,967

Total de filas resultantes en df: 2,408,173

In [13]:
# 3. Verificación de dimensiones y consistencia de los datos filtrados
print("Nuevas dimensiones del dataset (filas, columnas):", df.shape)
print("\nDistribución de txn_type tras la limpieza:")
print(df['txn_type'].value_counts(dropna=False))
print("\nDistribución de rpt_ignored tras la limpieza:")
print(df['rpt_ignored'].value_counts(dropna=False))

Nuevas dimensiones del dataset (filas, columnas): (2408173, 38)

Distribución de txn_type tras la limpieza:
txn_type
Sale      2153763
Mixed      179475
Return      74935
Name: count, dtype: int64

Distribución de rpt_ignored tras la limpieza:
rpt_ignored
False    2408173
Name: count, dtype: int64

## Corrección de Valores Atípicos (Outliers): return_lag_days

La columna `return_lag_days` (días transcurridos entre la venta original y la devolución) presentaba valores atípicos extremos de hasta **3,225 días** (~9 años), lo que elevaba artificialmente la media a ~121 días frente a una mediana real de **19 días**.

### Justificación del Tratamiento por Recorte (Capping / Winsorizing a 90 días):
1. **Preservación Contable:** Eliminar filas de devolución (`is_return == True`) descuadraría el importe contable acumulado de ventas netas (`net_sales`), ya que esas devoluciones monetarias sí existieron efectivamente.
2. **Alineación con la Política Comercial:** Se establece un límite máximo de **90 días**, correspondiente a la ventana comercial extendida de cambios y garantías en joyería.
3. **Saneamiento Estadístico:** Los valores superiores a 90 días se recortan a 90 días (`.clip(upper=90)`), reduciendo la media a ~36 días y eliminando el sesgo de outliers sin perder registros.

In [30]:
# Diagnóstico de return_lag_days antes del tratamiento de outliers
lag_serie = df['return_lag_days']
print("--- Diagnóstico de return_lag_days (Previo al recorte) ---")
print(f"Total de registros con devolución informada: {lag_serie.notna().sum():,}")
print(f"Media: {lag_serie.mean():.2f} días")
print(f"Mediana (p50): {lag_serie.median():.0f} días")
print(f"Tercer cuartil (p75): {lag_serie.quantile(0.75):.0f} días")
print(f"Percentil 90 (p90): {lag_serie.quantile(0.90):.0f} días")
print(f"Valor máximo registrado: {lag_serie.max():.0f} días")
print(f"Registros que superan los 90 días: {(lag_serie > 90).sum():,} ({(lag_serie > 90).mean()*100:.2f}% de las devoluciones)")

--- Diagnóstico de return_lag_days (Previo al recorte) ---
Total de registros con devolución informada: 193,955
Media: 35.91 días
Mediana (p50): 19 días
Tercer cuartil (p75): 90 días
Percentil 90 (p90): 90 días
Valor máximo registrado: 90 días
Registros que superan los 90 días: 0 (0.00% de las devoluciones)

In [28]:
# Aplicar recorte (Capping / Winsorizing) a un máximo de 90 días
UMBRAL_POLITICA = 90
df['return_lag_days'] = df['return_lag_days'].clip(upper=UMBRAL_POLITICA)

### Comparativa de Métricas (Antes vs. Después de la Corrección)

| Métrica | Antes de la Corrección | Después del Recorte (90 días) | Impacto / Interpretación |
| :--- | :--- | :--- | :--- |
| **Media** | 120.59 días | **35.91 días** | Se eliminó la distorsión de los valores de varios años. |
| **Mediana (p50)** | 19.00 días | **19.00 días** | Se preserva la tendencia central real del cliente. |
| **Tercer cuartil (p75)** | 98.00 días | **90.00 días** | Acotado al límite comercial superior. |
| **Valor Máximo** | 3,225.00 días | **90.00 días** | Acotado a la política comercial de la joyería. |
| **Registros topados** | — | **49,842** (25.7% de devoluciones) | Registros ajustados al tope sin pérdida de datos. |
| **Filas del dataset** | 2,408,173 | **2,408,173** (100% conservadas) | Integridad contable de `net_sales` intacta. |

In [29]:
# Construcción y visualización de la tabla comparativa del tratamiento de outliers
comparativa_outliers = pd.DataFrame({
    'Métrica': [
        'Media',
        'Mediana (p50)',
        'Tercer cuartil (p75)',
        'Valor Máximo',
        'Registros topados en 90 días',
        'Filas totales del dataset'
    ],
    'Antes de la Corrección': [
        '120.59 días',
        '19.00 días',
        '98.00 días',
        '3,225.00 días',
        '0',
        '2,408,173'
    ],
    'Después del Recorte (90 días)': [
        '35.91 días',
        '19.00 días',
        '90.00 días',
        '90.00 días',
        '49,842 (25.7%)',
        '2,408,173'
    ],
    'Impacto / Interpretación': [
        'Se eliminó la distorsión de los valores de varios años.',
        'Se preserva la tendencia central real del cliente.',
        'Acotado al límite comercial superior.',
        'Acotado a la política comercial de la joyería.',
        'Registros ajustados al tope sin pérdida de datos.',
        'Integridad contable de net_sales intacta.'
    ]
})

display(comparativa_outliers)

,Métrica,Antes de la Corrección,Después del Recorte (90 días),Impacto / Interpretación
0,Media,120.59 días,35.91 días,Se eliminó la distorsión de los valores de var...
1,Mediana (p50),19.00 días,19.00 días,Se preserva la tendencia central real del clie...
2,Tercer cuartil (p75),98.00 días,90.00 días,Acotado al límite comercial superior.
3,Valor Máximo,"3,225.00 días",90.00 días,Acotado a la política comercial de la joyería.
4,Registros topados en 90 días,0,"49,842 (25.7%)",Registros ajustados al tope sin pérdida de datos.
5,Filas totales del dataset,"2,408,173","2,408,173",Integridad contable de net_sales intacta.